### ISSUE TITLE
Change xmlTagName highlight group when it is patched

### ISSUE THREAD

**Issue by rbong** [gruvbox-community/gruvbox#104]
See #103 - we are waiting on the Vim XML syntax to be patched to contain the tag name in the end tag

**Comment by dimbleby** [comment]
vim/vim#884

**Comment by rbong** [comment]
I have also sent an email to the xml runtime file syntax maintainer, since it seems you're expected to contact the maintainer for runtime files rather than submit a pull request.

**Comment by dimbleby** [comment]
The syntax fix has now made it into the Vim codebase - as at vim/vim@96f45c0.

Of course it will be some time before most users pick that up.

**Comment by rbong** [comment]
It's now been a year... I'm returning the tag color to blue. Workaround if you are using an old version to return the tag color to aqua:

```
autocmd ColorScheme gruvbox hi! link xmlTagName GruvboxAquaBold
```
