### ISSUE TITLE
Python Function highlighting once declared.

### ISSUE THREAD

**Issue by lanox** [gruvbox-community/gruvbox#105]
Hi,

I was wondering if we could add function highlighting once the function has be declared.

I have this in my vimrc as workaround, however I was wondering if we could just add it in?

```
augroup python_syntax
       au!
       au FileType python syntax match pythonFunction /\v([^[:cntrl:][:space:][:punct:][:digit:]]|_)([^[:cntrl:][:punct:][:space:]]|_)*\ze(\s?\()/
       hi! link pythonFunction GruvboxAqua
augroup END
```

Thanks.

**Comment by lanox** [comment]
Hi, any chance of this been added to gruvbox ? Thanks

**Comment by rbong** [comment]
I'm not sure what this does differently from [this line](https://github.com/gruvbox-community/gruvbox/blob/6618b4497e2361d2c665c20cb06e20db72ea6adb/colors/gruvbox.vim#L1121). Could you please explain?

**Comment by lanox** [comment]
Problem is that it colours in the function when you declaring it, however when you actually use the function it is not coloured . 

let's say:

```
def fun(): <-- fun function will be coloured 
    print(“hello world.”)
```
```
fun() <-- calling function will not be coloured.
````

**Comment by rbong** [comment]
Gruvbox does not define the syntax matching for `pythonFunction`, it only colors what's there. The syntax matching is declared in [the vim runtime files](https://github.com/vim/vim/blob/e7eb92708ec2092a2fc11e78703b5dcf83844412/runtime/syntax/python.vim#L131), or if you have it installed, it may be defined through [vim-python/python-syntax](https://github.com/vim-python/python-syntax/blob/1df5e5aaf8c7050795e2994329a23b3fd24eb161/syntax/python.vim#L88) (or another alternate vim syntax plugin).

It would be more appropriate to submit a patch or point out the problem to the [python runtime syntax maintainer](https://github.com/vim/vim/blob/e7eb92708ec2092a2fc11e78703b5dcf83844412/runtime/syntax/python.vim#L3), or to submit a pull request or issue to [vim-python/python-syntax](https://github.com/vim-python/python-syntax).

**Comment by lanox** [comment]
Ah okay, thanks.
