### ISSUE TITLE
Digraph characters are hard to see

### ISSUE THREAD

**Issue by aos** [gruvbox-community/gruvbox#106]
Hey there! Thanks for maintaining gruvbox! It's my favorite colorscheme by far. I did notice a small issue with the character color of digraphs (invoked via `:digraphs`):

![image](https://user-images.githubusercontent.com/25783780/59893228-41d96380-93aa-11e9-99d7-c5a6486b7445.png)

As you can see, they are very hard to see, although not _impossible_. Do you by any chance know which highlight group is used to color them? If so, I'll gladly submit a PR to fix this!

**Comment by rbong** [comment]
The highlight group used is `SpecialKey`
