### ISSUE TITLE
Switch terminal color codes of aqua and neutral blue

### ISSUE THREAD

**Issue by hupfdule** [gruvbox-community/gruvbox#109]
I think you did the wrong thing in #60.

You switched aqua (#427b58) from 66 to 65, but left neutral blue (#458588) at 66.

Looking at the colors from a script that displays the terminal colors like [print256colours.sh](https://gist.github.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263) it should be the other way around. The color with code 66 has exactly the same hex value as gruvbox' aqua.

However the hex value for gruvbox' neutral blue is not that obvious. I think 24 is the one that is nearest to it and that should be the one that should be changed.

So I propose to

- change terminal color code of aqua back to 66
- change terminal color code of neutral bue to 24

Please see that attached image that (hopefully) shows what I mean.

![colors](https://user-images.githubusercontent.com/36069345/60520915-83d9a200-9ce6-11e9-8824-4727d7e783c8.png)

**Comment by hupfdule** [comment]
Damn! I just saw that 24 is already taken by bright blue (with exactly the same hex value). So it needs to be  some other color code for neutral blue. Maybe 30?

**Comment by rbong** [comment]
What terminal setup are you using? In both Alacritty and rxvt I get `5f8787` for 66. That is the generally accepted color code according to this 256 color xterm reference: https://jonasjacek.github.io/colors/

You may be using a config file that sets 66 to gruvbox-light dark-aqua, in which case it needs to be updated. However if there is still a more close approximation to light blue and dark aqua I am happy to switch it.

**Comment by hupfdule** [comment]
That's a bit strange. Se below an example where I have done this test with 
- kitty with [this configuration](https://github.com/morhetz/gruvbox-contrib/pull/83/commits/323b3c725f84239a806bbd69ef2c4c6fa741cce9#diff-9a6b228761e4d25c46c3495791ffd4c9)
- kitty with the default configuration
- urxvt with solarized colors (specified via .Xdefaults)
- lxterminal with the default configuration

In all cases except the solarized urxvt the hex value of 66 is `427b58`.

![multiple](https://user-images.githubusercontent.com/36069345/60572925-e7131500-9d76-11e9-8d97-6bed37c25dac.png)

I now did a test with a different virtual machine and tried it with urxvt, xterm, lxterminal and uxterm.
And there I get a hex value of `5f8787`. 

That seems a bit strange to me. I would have expected that the modifications to my .Xdefaults can be a problem, but neither lxterminal nor kitty should be influenced by these modifications.

**Comment by hupfdule** [comment]
Since `5f8787` seems to be the correct color for code 66, I think you have done it right and I suggest you close this issue.

But it still puzzles me what is different in my system that even kitty and lxterminal get different colors…

**Comment by rbong** [comment]
Are you perhaps sourcing the [gruvbox 256 color palette script](https://github.com/morhetz/gruvbox/blob/master/gruvbox_256palette.sh) somewhere in your shell?

**Comment by hupfdule** [comment]
Of course! I just forgot that and therefore was surprised of the outcome.
Thank you for pointing me to that.
