### ISSUE TITLE
Weird highlight with easymotion

### ISSUE THREAD

**Issue by SeraphRoy** [gruvbox-community/gruvbox#111]
When use easymotion with `<Leader><Leader>w`(`<Plug>(easymotion-w)`), the styles of highlight are different for single-character jumps and multi-character jumps. For single character jumps gruvbox highlights the background but for multi-character jumps gruvbox highlights the actual characters. See the following screenshot after the use of `<Leader><Leader>w`(`<Plug>(easymotion-w)`).

<img width="395" alt="Screen Shot 2019-07-10 at 16 43 46" src="https://user-images.githubusercontent.com/13044821/61012109-ef002580-a331-11e9-8176-4e4ab31196a1.png">

**Comment by rbong** [comment]
I am more likely to be able to recreate this issue if you provide a minimal test case.

**Comment by SeraphRoy** [comment]
Yeah sorry tried with the following minimal config and still the same issue.

```
" vim-plug begin
call plug#begin('~/.vim/bundle')
Plug 'gruvbox-community/gruvbox'
Plug 'easymotion/vim-easymotion'
call plug#end()

" <Leader> = ' '
let mapleader=" "

" Syntax Highlight
syntax on

" 256 color
set termguicolors
" let &t_Co=256

" color scheme/theme
syntax enable
set background=dark
let g:gruvbox_italic = 1
let g:gruvbox_invert_indent_guides = 1
let g:gruvbox_contrast_dark = 'soft'
colorscheme gruvbox
```

**Comment by SeraphRoy** [comment]
Not sure about minimal test case though because you need the text to be kinda long enough to make easymotion to create both one and two character jumps. Here's my minimum test case though

```
abcbc abc abc abc abc abc abc
abcbc abc abc abc abc abc abc
abcbc abc abc abc abc abc abc
abcbc abc abc abc abc abc abc
abcbc abc abc abc abc abc abc
abcbc abc abc abc abc abc abc
```

<img width="345" alt="Screen Shot 2019-07-11 at 10 02 20" src="https://user-images.githubusercontent.com/13044821/61070234-05a28d00-a3c3-11e9-86fe-e53a3253f6f1.png">

**Comment by SeraphRoy** [comment]
Update:

Adding 

`hi link EasyMotionTarget GruvboxYellowBold` 

after 

`colorscheme gruvbox` 

fixes the issue. Might be worth to add that into the theme itself?

**Comment by rbong** [comment]
Thank you for the fix. The group is currently linked to the search highlight group, which relies on inverting colors, potentially causing this problem. I have not tested the fix, but I also do not use easymotion. I have added the fix. If anyone who uses easymotion can confirm that it works well, please let me know.

**Comment by bronzehedwick** [comment]
I can confirm the fix working as expected.

![Screen Shot 2019-09-18 at 3 33 49 PM](https://user-images.githubusercontent.com/637174/65179947-cb401680-da29-11e9-8fec-528fb5f42431.png)

@SeraphRoy is this issue resolved to your satisfaction as well?

**Comment by SeraphRoy** [comment]
Sorry for the late reply and yes it works for me. Thanks all!
