### ISSUE TITLE
CSS properties get different colors

### ISSUE THREAD

**Issue by bronzehedwick** [gruvbox-community/gruvbox#114]
Some CSS properties get the green color, some get the yellow, and still others get orange. They should all be the same color.

Example below:

![Screen Shot 2019-08-08 at 3 45 52 PM](https://user-images.githubusercontent.com/637174/62732976-a18bdc80-b9f3-11e9-83d9-84471d27aab3.png)

**Comment by sainnhe** [comment]
css properties are linked to `cssProp`, maybe [these codes](https://github.com/gruvbox-community/gruvbox/blob/79f0551962fd0d99e6a779f6bd125807d5d9b376/colors/gruvbox.vim#L1153-L1173) can be replaced with

```vim
hi! link cssProp GruvboxAqua
```

**Comment by bronzehedwick** [comment]
Hm so it looks like this color difference is intentional, and I was just not aware of the groups that are being used. 

Do others find that valuable, to know the general type of thing the css property effects via the prop color?

I personally don’t find that information useful and it adds to visual noise for me, but if others like this I can override in my own config.

**Comment by rbong** [comment]
I personally wouldn't feel comfortable removing it unless if there's a huge consensus, given that it's long-time intentional behaviour and it's a bit easier to disable than it would be to re-enable.

**Comment by bronzehedwick** [comment]
Fair enough @rbong, I'll disable in my config. Thanks!
