### ISSUE TITLE
`Last Modified` date of `gruvbox.vim` still says ` 12 Aug 2017`

### ISSUE THREAD

**Issue by ericdorsey** [gruvbox-community/gruvbox#119]
Looks like this community fork of `gruvbox` is pretty active, but https://github.com/gruvbox-community/gruvbox/blob/master/colors/gruvbox.vim#L6 still says:

```
" Last Modified: 12 Aug 2017
```

Minor deal, but should that be updated to reflect the last commit? Or is that not meant to be updated when `/colors/gruvbox.vim` is updated?

**Comment by rbong** [comment]
Thanks, I have removed the last modified date for now. The payoff of keeping this information up to date is not worth it. If there is a better way to update this information or we get more maintainers and they want to keep this information up to date, we can add it back.
