### ISSUE TITLE
Lightline with gruvbox

### ISSUE THREAD

**Issue by kaatish** [gruvbox-community/gruvbox#125]
Is lightline actually supported by gruvbox with neovim?

This is what it looks like currently :
![gruvbox_lightline](https://user-images.githubusercontent.com/2610638/71685446-55588480-2d66-11ea-8d6d-2bafce1e68c6.png)

The code highlighting looks perfect and I have no issues with that.

My init.vim looks like this :
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'gruvbox-community/gruvbox'
Plug 'itchyny/lightline.vim'
call plug#end()

set termguicolors
set background=dark
let g:gruvbox_contrast_dark = 'hard'
colorscheme gruvbox

```
Right now I am not sourcing gruvbox_256palette.sh, however doing that does not change things.
I am using neovim version 0.4.3 on gnome terminal.

**Comment by danbruegge** [comment]
You have to tell lightline which theme it should use.

`let g:lightline = {
    \ 'colorscheme': 'gruvbox',
\ }
`

**Comment by kaatish** [comment]
That worked.
