### ISSUE TITLE
Some colors are different for Ruby

### ISSUE THREAD

**Issue by fladson** [gruvbox-community/gruvbox#130]
Hey folks, I am not sure why but some keywords are off for me with ruby files.
I have tested this on multiple terminals, nvim and vim, outside tmux but I can't get the same colors seen on the screenshots.
![Screenshot from 2020-03-24 21-54-37](https://user-images.githubusercontent.com/554507/77476034-13495700-6e1a-11ea-8c56-fcf2d7e5f439.png)

`private` and `attr_reader` are some examples, they should be red per the screenshots.
I am not sure if the screenshots are old and the color for those keywords changed.

On that screenshot I am using `nvim 0.4.3`, kitty terminal, outside tmux with a minimal config, not running the sh script
```
Plug 'gruvbox-community/gruvbox'
set termguicolors
colorscheme gruvbox
```

Any clue why?
Thank you

**Comment by rbong** [comment]
I think the screenshots are critically out of date or inaccurate. Constants have always been purple, so the screenshots were either taken before the plugin was finalized, they were taken with some additional configuration or plugins, or the ruby syntax has been updated.
