### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by ejiek** [gruvbox-community/gruvbox#134]
I've noticed that gruvbox-community has only one release after forking from gruvbox while the rest itself is alive and well.

There is a need for releases from package maintainers ([here one from AUR](https://aur.archlinux.org/packages/vim-gruvbox-community/)).

So can you please bump the version occasionally if it's not too much of a burden =]

**Comment by rbong** [comment]
Sorry about that, I didn't even know we had packages! Updated.
