### ISSUE TITLE
Gruvbox adds bg color to error highlights making text hard to read

### ISSUE THREAD

**Issue by bdielman** [gruvbox-community/gruvbox#137]
In this case the `no unused vars` error displays with the bg and fg colors in a way that makes the text hard to read. When checked with other color schemes, the error displays with a simple underline.

<img width="257" alt="Screen Shot 2020-06-14 at 11 37 44 AM" src="https://user-images.githubusercontent.com/94547/84597903-fb8bd880-ae34-11ea-9928-22a15580d7d8.png">

**Comment by rishabhdeepsingh** [comment]
Also facing the same issue with search as well
<img width="173" alt="Screenshot 2020-06-26 at 6 52 57 AM" src="https://user-images.githubusercontent.com/28526643/85810791-ca3ad300-b779-11ea-8325-6d4a051160b7.png">

**Comment by lanox** [comment]
@rishabhdeepsingh  you can change the color of that.

```
g:gruvbox_hls_cursor

Changes cursor background while search is highlighted. Possible values are any of gruvbox palette.
default: orange
```

**Comment by rishabhdeepsingh** [comment]
@lanox I set that but now it is showing white instead of what I am setting

```
let g:gruvbox_contrast_dark='dark'
let g:gruvbox_hls_cursor='red'
colorscheme gruvbox
set background=dark
```

**Comment by GGCristo** [comment]
Same here
![Screenshot_20200820_134012](https://user-images.githubusercontent.com/58046649/90771856-c9429f80-e2eb-11ea-9663-5cd45d0aa76b.png)
