### ISSUE TITLE
Vim filetype highlighting 

### ISSUE THREAD

**Issue by craigmac** [gruvbox-community/gruvbox#145]
* Vim version 8.2.1800
* Alacritty 0.5.0 and Terminal.app and iTerm2 latest
* Mac OS X 10.15.6 (Catalina)

I believe this is a $VIMRUNTIME/syntax/vim.vim issue, and I've contacted the maintainer (via email as the vim github tracker says to do for $VIMRUNTIME issues), but I thought it might be a quick fix for someone here to tackle.

Steps to reproduce:
1. `vim --clean`
2. `:edit /tmp/foo.vim`
3. enter: `source $VIMRUNTIME/defaults.vim`
4. enter: `packadd! vim-fugitive`

Notice 'defaults.vim' ending '.vim' is coloured when it should not be, and 'vim-' part of 'vim-fugitive' is coloured when it should not be.

The same issue exists when you do the above steps but are using `colorscheme gruvbox` (from this repo).

![Screen Shot 2020-10-05 at 11 02 21 AM](https://user-images.githubusercontent.com/7416158/95099184-96b6ff80-06fd-11eb-87be-d9a93c6878bc.png)
![Screen Shot 2020-10-05 at 10 53 16 AM](https://user-images.githubusercontent.com/7416158/95099188-97e82c80-06fd-11eb-9996-f4256a13539d.png)

**Comment by rbong** [comment]
Nothing we can do, we don't define syntax groups, just colors for those syntax groups.
