### ISSUE TITLE
Highlight for treesitter TSKeywordOperator 

### ISSUE THREAD

**Issue by luisiacc** [gruvbox-community/gruvbox#153]
I checked it out on the code and gruvbox does not highlight `TSKeywordOperator` from treesitter, perhaps others, I think it should. 
More reference on this can be found here: [https://github.com/nvim-treesitter/nvim-treesitter/issues/447](https://github.com/nvim-treesitter/nvim-treesitter/issues/447)

**Comment by rouge8** [comment]
I opened a PR for this: https://github.com/gruvbox-community/gruvbox/pull/175

**Comment by rbong** [comment]
Thanks for the PR and sorry for the delay, let me know if there are any problems.
