### ISSUE TITLE
Gitsings colors are almost indistinguishable

### ISSUE THREAD

**Issue by MaxVerevkin** [gruvbox-community/gruvbox#181]
Currently, green color is used for "Add" and aqua for "Change". My issue is that they are very similar and it's not obvious what is what:

![image](https://user-images.githubusercontent.com/34583604/158880842-95aa09d7-6eba-46dd-9f61-861cffc3c901.png)

I propose using aqua for "Add" and orange for "Change":

![image](https://user-images.githubusercontent.com/34583604/158881145-a99abd92-4c68-46d2-9cb2-32bfe04d2bf1.png)

_Originally posed in https://github.com/ellisonleao/gruvbox.nvim/issues/106_

**Comment by MaxVerevkin** [comment]
@ellisonleao any thoughts?

**Comment by ellisonleao** [comment]
@rbong any thoughts?

**Comment by ellisonleao** [comment]
@MaxVerevkin I haven't tried that yet, but did you get a chance to compare the add color in VSCode's gruvbox and also the original version to see if they are using another color for that?

**Comment by MaxVerevkin** [comment]
@ellisonleao vscode:

![image](https://user-images.githubusercontent.com/34583604/163726604-7969d386-63f2-4bf8-9074-34adbc2c3997.png)

**Comment by MaxVerevkin** [comment]
> the original version

Not sure what you are referring to

**Comment by rbong** [comment]
@ellisonleao how is orange working for you? Any complaints?

**Comment by ellisonleao** [comment]
@rbong LGTM
