### ISSUE TITLE
gruvbox 3.0.0 removes most Python highlighting when used with nvim-treesitter

### ISSUE THREAD

**Issue by rouge8** [gruvbox-community/gruvbox#191]
# Summary

I updated from 2b5b1f777f0583ffb39086d6c16f39e6e37459c0 to e8b59655db4323ee3b7bfd2714e47760dcb84406 this morning and most of the Python highlighting was gone.

Given this file:

```python
import enum
from typing import assert_never


class MyEnum(enum.Enum):
    a = "a"
    b = "b"

    @property
    def something(self) -> int:
        match self:
            case self.a:
                return 1
            case self.b:
                return 2
            case _:
                assert_never(self)
```

Here's what it looked like before:

![before](https://github.com/gruvbox-community/gruvbox/assets/237005/2c7f9957-9fab-4118-a00e-6f96cccbaa05)

Here's what it looks like after updating:

![after](https://github.com/gruvbox-community/gruvbox/assets/237005/418e005d-627c-45c0-82eb-87b59bc774e7)

# vim version

```
❯ nvim --version
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"

Run :checkhealth for more info
```

# Terminal

```
kitty 0.29.2 created by Kovid Goyal
```

# vimrc

```vim
call plug#begin(stdpath('data') . '/plugged')

Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'gruvbox-community/gruvbox'

call plug#end()

lua <<EOF
require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "python",
    },
    ignore_install = {},
    highlight = {
        enable = true,
        disable = {},
        additional_vim_regex_highlighting = false,
    },
})
EOF

set background=dark
colorscheme gruvbox
```

This won't exactly match the screenshots (no line numbers for example) but it is enough to reproduce the highlighting changes.

**Comment by rbong** [comment]
Normal variables are now white. This is consistent with many of the previous language appearances. If you'd like to change this, you can change `@variable`:

```
autocmd ColorScheme gruvbox hi! link @variable GruvboxBlue
```

If you'd like to know the group under the cursor so you can replace it, use `:Inspect`.

`enum`, `typing`, and `assert_never` are simply linked to `@variable` and can't be distinguished from normal variables, this is a TreeSitter parser problem.

`@property` should have distinguished highlighting when you pull changes. However, the group for `@` in `@property` is overwritten by the property group. Not sure if this is a TreeSitter or parser problem.

`self` is a builtin in Python, this should now be distinguished on pull.

Here's how it looks now:

![2023-09-12-131604_382x351_scrot](https://github.com/gruvbox-community/gruvbox/assets/5875706/61dcc9f7-53e6-4a67-a0c2-d09fec560542)

**Comment by rbong** [comment]
There have been some more tweaks to highlight groups, you might want to pull to make sure you're still happy with it and any customizations you made still look good, see [this comment](https://github.com/gruvbox-community/gruvbox/pull/188#issuecomment-1722553465).
