### ISSUE TITLE
Regular status line looks a little off...

### ISSUE THREAD

**Issue by rbong** [gruvbox-community/gruvbox#29]
So, not using any form of juiced status line, looks a little off.

In the attached screenshot it looks like the colors are inverted. - The split on the right is the focused one, but judging by the status line, it looks to be the other way around (to my eyes, at least).

Not sure if this is a bug or intended. So far I've hacked a dirty fix but I know nothing about theming Vim, so I thought I'd drop you an issue.

EDIT: Comparing your screenshots to my own sorta makes me realize that there might be something fundamentally wrong with the colors on my machine, no? - I **have** added _set termguicolors_ as per [your instructions](https://github.com/morhetz/gruvbox/wiki/Terminal-specific) and are using Neovim/ConEmu, by the time the screenshot was taken, though.

![gruvbox_weird_statusline](https://cloud.githubusercontent.com/assets/6486383/23760125/0a6292ba-04ef-11e7-8e11-00a8b5015bbc.PNG)

:robot: **This issue has been automatically copied from morhetz#164** :robot:

**Comment by bronzehedwick** [comment]
@rbong Is this issue still happening for you? I see a more faded color of text in the un-focused window, but not nearly as much as the screen shot above. Here's mine:

![Screen Shot 2019-09-18 at 4 01 45 PM](https://user-images.githubusercontent.com/637174/65181800-dc8b2200-da2d-11e9-985a-b66465614a15.png)

**Comment by rbong** [comment]
@bronzehedwick seems like the [original issue author](https://github.com/morhetz/gruvbox/issues/164#issuecomment-285417455) uses ConEmu. Seems like a typical terminal-specific problem that we get a lot of, no response for 2 years... I'm just going to close this for now. Issues like this are typically just the terminal not rendering colors correctly... nothing we can do.

If someone finds this issue trying to get ConEmu to work or the original author comes back and I'm wrong, please reopen. Otherwise please debug and open an issue with Neovim/ConEmu since other terminals render the theme correctly.
