### ISSUE TITLE
A suggestion for error foreground color

### ISSUE THREAD

**Issue by rbong** [gruvbox-community/gruvbox#38]
A small suggestion to change the error message foreground color from:

``` VimL
call s:HL('ErrorMsg',   s:vim_bg, s:red, s:bold)
```

to

``` VimL
call s:HL('ErrorMsg',   s:fg0, s:red, s:bold)
```

This is more readable due to better contrast.

:robot: **This issue has been automatically copied from morhetz#138** :robot:

**Comment by bronzehedwick** [comment]
Is this issue still relevant? It no longer seems ErrorMsg uses `s:vim_bg`, but I could be confused, since there is a lot of logic tracing needed to figure out what the color variables are (IMO).

**Comment by rbong** [comment]
You're right, this issue is no longer relevant, it uses `bg0` right now. Thank you for catching that.
