### ISSUE TITLE
Not setting the background contrast mode as expected

### ISSUE THREAD

**Issue by rbong** [gruvbox-community/gruvbox#4]
At the end of my init.vim I have this line
```
let g:gruvbox_contrast_dark = 'hard'
```
as per the documentation on the wiki for setting the background contrast mode. However, when I load Neovim, the change is not applied; when I `:so $MYVIMRC` it applies the changes. Am I doing something wrong here?

![example](https://user-images.githubusercontent.com/10568042/51131685-b8d56380-1830-11e9-82b1-1da8d2ba6cea.gif)

:robot: **This issue has been automatically copied from morhetz#258** :robot:

**Comment by bronzehedwick** [comment]
@rbong Is this still an issue? I am unable to replicate via the above steps (in fact I use hard contrast day-to-day) in neovim.

Here's my neovim version:

```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-42760-1cnn23a/neovim-0.4.2/build/config -I/tmp/neovim-20190916-42760-1cnn23a/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-42760-1cnn23a/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20190916-42760-1cnn23a/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-42760-1cnn23a/neovim-0.4.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```

**Comment by rbong** [comment]
It seems like the original issue was just not putting the variable before gruvbox is loaded, which is a common mistake. The original issue also contains an [additional error](https://github.com/morhetz/gruvbox/issues/258#issuecomment-459791906). That one is a little harder to track down - it appears to be [an error from a much older version](https://github.com/morhetz/gruvbox/issues/258#issuecomment-497605485) but no response from the original commenter as to whether it's fixed when they update.

**Comment by rbong** [comment]
It's been confirmed by multiple people now that this can be resolved by putting variables in the proper spot, closing this.
