### ISSUE TITLE
gruvbox golang

### ISSUE THREAD

**Issue by rbong** [gruvbox-community/gruvbox#56]
Hi, 

Are you still supporting this theme ?

I just wanted to ask you if something has changed in gruvbox theme for golang support, looking at the gallery for golang see below.

my system.
<img width="1032" alt="screen shot 2018-10-03 at 12 45 20 am" src="https://user-images.githubusercontent.com/7599183/46356365-f1986500-c6a5-11e8-824e-33db849150d4.png">

this is image from gallery you have posted.

![687474703a2f2f696d6775722e636f6d2f7535796e7264432e706e67](https://user-images.githubusercontent.com/7599183/46356391-0248db00-c6a6-11e8-98cc-08872e01d58b.png)

as you can see the imports are different color, just wondering is that normal, or are my colors screwed up.

Thanks

:robot: **This issue has been automatically copied from morhetz#254** :robot:

**Comment by bronzehedwick** [comment]
Huh, I copied some of this code into a test file, and got something similar to the original author's screenshot in alacritty/neovim.

<img width="1025" alt="Screen Shot 2019-09-18 at 8 49 42 PM" src="https://user-images.githubusercontent.com/637174/65200721-f4769c00-da55-11e9-9ea3-6298cefb4a0a.png">

I get something similar in iTerm2/neovim.

<img width="892" alt="Screen Shot 2019-09-18 at 8 51 25 PM" src="https://user-images.githubusercontent.com/637174/65200753-225be080-da56-11e9-853b-7a9735eaa032.png">

Which terminal were you using? And vim or neovim?

Thanks!

**Comment by bryceyang** [comment]
are u using vim-go plug? vim-go has changed default go syntax highlighting config.

**Comment by bronzehedwick** [comment]
Ah good point, I am not using vim-go. Is that the source of the difference?

**Comment by bryceyang** [comment]
I think that's the reason.I am using vim-go. And the highlight style of mine is just like rbong‘’s screenshots. The go.vim in vim-go repository configured the import and package keyword as Statement, which will be displayed as red in gruvbox theme.
