### ISSUE TITLE
Tex support

### ISSUE THREAD

**Issue by rbong** [gruvbox-community/gruvbox#98]
Support highlighting for *.tex files

**Comment by shuber2** [comment]
I am using gruvbox and latex (with lervag/vimtex plugin) for quite some time, so I wonder what actually are you missing here from gruvbox?

**Comment by rbong** [comment]
@shuber2 good catch. It's not clear to me why I opened this from the comment in #19. If there is a specific issue with *.tex highlighting, someone can open an issue or MR. I don't use it regularly myself, so I think I just opened it because the original migrated issue mentioned that latex wasn't officially supported.
